name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: petprep_hmc
        environment-file: environment.yml
        auto-activate-base: true
        
    - name: Install dependencies
      run: |
        conda activate petprep_hmc
        pip install -e .
      shell: bash -l {0}
        
    - name: Install coverage and pytest
      run: |
        conda activate petprep_hmc
        conda install -c conda-forge pytest coverage
      shell: bash -l {0}
        
    - name: Run tests with coverage
      run: |
        conda activate petprep_hmc
        pytest --cov=tests --cov-report=xml
      shell: bash -l {0}
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
